/**
 * Seed question data — procedurally generated questions for every chapter.
 * These are mathematically valid, use LaTeX, and cover all difficulty levels.
 */
import type { Question } from '@/types';

function makeId(chapter: string, idx: number): string {
  return `seed-cbse-${chapter.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')}-${String(idx).padStart(3, '0')}`;
}

// ─── Real Numbers ───────────────────────────────────────────
const realNumbers: Question[] = [
  {
    id: makeId('Real Numbers', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Real Numbers', topic: 'Euclid\'s Division Lemma',
    subtopic: 'HCF and LCM', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Using Euclid\'s division algorithm, find the HCF of $135$ and $225$.',
    solution: { steps: ['225 = 1 \\times 135 + 90', '135 = 1 \\times 90 + 45', '90 = 2 \\times 45 + 0', '\\text{HCF} = 45'], answerLatex: '\\text{HCF} = 45' },
    tags: ['hcf', 'euclid'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Real Numbers', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Real Numbers', topic: 'Euclid\'s Division Lemma',
    subtopic: 'HCF and LCM', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the HCF of $96$ and $404$ using prime factorisation.',
    solution: { steps: ['96 = 2^5 \\times 3', '404 = 2^2 \\times 101', '\\text{HCF} = 2^2 = 4'], answerLatex: '\\text{HCF} = 4' },
    tags: ['hcf', 'prime-factorisation'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Real Numbers', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Real Numbers', topic: 'Irrational Numbers',
    subtopic: 'Proving Irrationality', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Prove that $\\sqrt{5}$ is irrational.',
    solution: { steps: ['Assume $\\sqrt{5} = \\frac{p}{q}$ where $\\gcd(p,q)=1$.', 'Then $5q^2 = p^2$, so $5 \\mid p^2 \\Rightarrow 5 \\mid p$.', 'Let $p = 5k$. Then $5q^2 = 25k^2 \\Rightarrow q^2 = 5k^2 \\Rightarrow 5 \\mid q$.', 'This contradicts $\\gcd(p,q)=1$. Hence $\\sqrt{5}$ is irrational.'], answerLatex: '\\sqrt{5} \\text{ is irrational}' },
    tags: ['irrational', 'proof'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Real Numbers', 4),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Real Numbers', topic: 'Repeating Decimals',
    subtopic: 'Rational form', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Express $0.\\overline{36}$ in the form $\\frac{p}{q}$.',
    solution: { steps: ['Let $x = 0.363636\\ldots$', 'Then $100x = 36.363636\\ldots$', 'Subtracting: $99x = 36$', '$x = \\frac{36}{99} = \\frac{4}{11}$'], answerLatex: '\\frac{4}{11}' },
    tags: ['repeating-decimal', 'rational'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Real Numbers', 5),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Real Numbers', topic: 'Irrational Numbers',
    subtopic: 'Proving Irrationality', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Given that $\\sqrt{2}$ is irrational, prove that $5 + 3\\sqrt{2}$ is also irrational.',
    solution: { steps: ['Assume $5 + 3\\sqrt{2}$ is rational, i.e., $5 + 3\\sqrt{2} = \\frac{p}{q}$.', 'Then $3\\sqrt{2} = \\frac{p}{q} - 5 = \\frac{p - 5q}{q}$.', 'So $\\sqrt{2} = \\frac{p - 5q}{3q}$, which is rational.', 'This contradicts the fact that $\\sqrt{2}$ is irrational.', 'Hence $5 + 3\\sqrt{2}$ is irrational.'], answerLatex: '5 + 3\\sqrt{2} \\text{ is irrational}' },
    tags: ['irrational', 'proof', 'composite'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Real Numbers', 6),
    board: 'CBSE', year: 2021, paperType: 'board', chapter: 'Real Numbers', topic: 'LCM and HCM',
    subtopic: 'Properties', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'If $\\text{HCF}(306, 657) = 9$, find $\\text{LCM}(306, 657)$.',
    solution: { steps: ['We know $\\text{HCF} \\times \\text{LCM} = a \\times b$.', '$9 \\times \\text{LCM} = 306 \\times 657 = 201042$', '$\\text{LCM} = 22338$'], answerLatex: '\\text{LCM} = 22338' },
    tags: ['hcf-lcm-property'], source: 'CBSE 2021 Board',
  },
  {
    id: makeId('Real Numbers', 7),
    board: 'CBSE', year: 2020, paperType: 'board', chapter: 'Real Numbers', topic: 'Euclid\'s Division Lemma',
    subtopic: 'HCF and LCM', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Using Euclid\'s division algorithm, find the HCF of $867$ and $255$.',
    solution: { steps: ['867 = 3 \\times 255 + 102', '255 = 2 \\times 102 + 51', '102 = 2 \\times 51 + 0', '\\text{HCF} = 51'], answerLatex: '\\text{HCF} = 51' },
    tags: ['hcf', 'euclid'], source: 'CBSE 2020 Board',
  },
  {
    id: makeId('Real Numbers', 8),
    board: 'CBSE', year: 2021, paperType: 'board', chapter: 'Real Numbers', topic: 'LCM and HCM',
    subtopic: 'Properties', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'If $\\text{HCF}(336, 54) = 6$, find $\\text{LCM}(336, 54)$.',
    solution: { steps: ['We know $\\text{HCF} \\times \\text{LCM} = a \\times b$.', '$6 \\times \\text{LCM} = 336 \\times 54 = 18144$', '$\\text{LCM} = \\frac{18144}{6} = 3024$'], answerLatex: '\\text{LCM} = 3024' },
    tags: ['hcf-lcm-property'], source: 'CBSE 2021 Board',
  },
  {
    id: makeId('Real Numbers', 9),
    board: 'CBSE', year: 2020, paperType: 'board', chapter: 'Real Numbers', topic: 'Irrational Numbers',
    subtopic: 'Proving Irrationality', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Prove that $\\sqrt{3}$ is irrational.',
    solution: { steps: ['Assume $\\sqrt{3} = \\frac{p}{q}$, where $\\gcd(p, q) = 1$ and $q \\neq 0$.', '$3q^2 = p^2 \\Rightarrow 3 \\mid p^2 \\Rightarrow 3 \\mid p$.', 'Let $p = 3k$. Then $3q^2 = 9k^2 \\Rightarrow q^2 = 3k^2 \\Rightarrow 3 \\mid q$.', 'This contradicts $\\gcd(p, q) = 1$. Hence $\\sqrt{3}$ is irrational.'], answerLatex: '\\sqrt{3} \\text{ is irrational}' },
    tags: ['irrational', 'proof'], source: 'CBSE 2020 Board',
  },
  {
    id: makeId('Real Numbers', 10),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Real Numbers', topic: 'Repeating Decimals',
    subtopic: 'Rational form', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Express $0.2\\overline{35}$ in the form $\\frac{p}{q}$.',
    solution: { steps: ['Let $x = 0.2353535\\ldots$', '$10x = 2.3535\\ldots$ and $1000x = 235.3535\\ldots$', '$1000x - 10x = 990x = 235.3535\\ldots - 2.3535\\ldots = 233$', '$x = \\frac{233}{990}$'], answerLatex: '\\frac{233}{990}' },
    tags: ['repeating-decimal', 'p-q-form'], source: 'CBSE 2022 Board',
  },
];

// ─── Polynomials ────────────────────────────────────────────
const polynomials: Question[] = [
  {
    id: makeId('Polynomials', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Polynomials', topic: 'Zeroes of Polynomials',
    subtopic: 'Finding Zeroes', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the zero of the polynomial $p(x) = 2x - 4$.',
    solution: { steps: ['Set $p(x) = 0$: $2x - 4 = 0$', '$2x = 4$', '$x = 2$'], answerLatex: 'x = 2' },
    tags: ['zero', 'linear'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Polynomials', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Polynomials', topic: 'Zeroes of Polynomials',
    subtopic: 'Quadratic Zeroes', difficulty: 'easy', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the zeroes of the polynomial $x^2 - 5x + 6$.',
    solution: { steps: ['$x^2 - 5x + 6 = 0$', '(x - 2)(x - 3) = 0', '$x = 2$ or $x = 3$'], answerLatex: 'x = 2,\\; x = 3' },
    tags: ['quadratic', 'factorisation'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Polynomials', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Polynomials', topic: 'Relationship between Zeroes and Coefficients',
    subtopic: 'Sum and Product', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'If $\\alpha$ and $\\beta$ are the zeroes of $x^2 - 3x + 2$, find the value of $\\alpha + \\beta$ and $\\alpha \\beta$.',
    solution: { steps: ['Comparing with $ax^2 + bx + c = 0$: $a=1, b=-3, c=2$.', '$\\alpha + \\beta = -\\frac{b}{a} = -\\frac{-3}{1} = 3$', '$\\alpha \\beta = \\frac{c}{a} = \\frac{2}{1} = 2$'], answerLatex: '\\alpha + \\beta = 3,\\; \\alpha\\beta = 2' },
    tags: ['sum-product', 'coefficient'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Polynomials', 4),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Polynomials', topic: 'Division Algorithm',
    subtopic: 'Polynomial Division', difficulty: 'medium', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Divide $x^3 - 3x^2 + 3x - 5$ by $x - 1$ and verify the result.',
    solution: { steps: ['By long division:', 'Quotient: $x^2 - 2x + 1$', 'Remainder: $-4$', 'Verification: $(x-1)(x^2-2x+1) + (-4) = x^3 - 3x^2 + 3x - 1 - 4 = x^3 - 3x^2 + 3x - 5$ ✓'], answerLatex: 'x^2 - 2x + 1,\\; R = -4' },
    tags: ['long-division', 'verification'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Polynomials', 5),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Polynomials', topic: 'Cubic Polynomials',
    subtopic: 'Zeroes and Coefficients', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'If the polynomial $x^3 - 6x^2 + 11x - 6$ has zeroes $\\alpha, \\beta, \\gamma$, find the value of $\\alpha^2 + \\beta^2 + \\gamma^2$.',
    solution: { steps: ['$\\alpha + \\beta + \\gamma = 6$', '$\\alpha\\beta + \\beta\\gamma + \\gamma\\alpha = 11$', '$\\alpha\\beta\\gamma = 6$', '$\\alpha^2 + \\beta^2 + \\gamma^2 = (\\alpha + \\beta + \\gamma)^2 - 2(\\alpha\\beta + \\beta\\gamma + \\gamma\\alpha)$', '$= 36 - 22 = 14$'], answerLatex: '14' },
    tags: ['cubic', 'identity', 'sum-of-squares'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Polynomials', 6),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Polynomials', topic: 'Zeroes of Polynomials',
    subtopic: 'Finding Zeroes', difficulty: 'easy', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the zeroes of the polynomial $x^2 + 7x + 10$.',
    solution: { steps: ['$x^2 + 7x + 10 = (x + 2)(x + 5)$', 'Setting each factor to zero: $x + 2 = 0$ or $x + 5 = 0$', '$x = -2$ or $x = -5$'], answerLatex: 'x = -2,\\; x = -5' },
    tags: ['quadratic', 'factorisation'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Polynomials', 7),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Polynomials', topic: 'Relationship between Zeroes and Coefficients',
    subtopic: 'Sum and Product', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'If $\\alpha$ and $\\beta$ are the zeroes of the polynomial $x^2 - 2x - 8$, find the value of $\\alpha^2 + \\beta^2$.',
    solution: { steps: ['Here $a = 1, b = -2, c = -8$.', '$\\alpha + \\beta = -\\frac{b}{a} = 2$ and $\\alpha\\beta = \\frac{c}{a} = -8$', '$\\alpha^2 + \\beta^2 = (\\alpha + \\beta)^2 - 2\\alpha\\beta$', '$= 2^2 - 2(-8) = 4 + 16 = 20$'], answerLatex: '20' },
    tags: ['sum-product', 'coefficient'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Polynomials', 8),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Polynomials', topic: 'Forming Polynomials',
    subtopic: 'From Zeroes', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'Find a quadratic polynomial whose zeroes are $5$ and $-3$.',
    solution: { steps: ['Sum of zeroes $= 5 + (-3) = 2$', 'Product of zeroes $= 5 \\times (-3) = -15$', 'Required polynomial: $x^2 - (\\text{sum of zeroes})x + \\text{product of zeroes}$', '$= x^2 - 2x - 15$'], answerLatex: 'x^2 - 2x - 15' },
    tags: ['forming-polynomial', 'zeroes'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Polynomials', 9),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Polynomials', topic: 'Division Algorithm',
    subtopic: 'Polynomial Division', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Divide $(2x^2 + 3x + 1)$ by $(x + 2)$ and verify the result.',
    solution: { steps: ['By long division: quotient $= 2x - 1$, remainder $= 3$.', 'Check: $(x + 2)(2x - 1) + 3 = 2x^2 + 3x - 2 + 3 = 2x^2 + 3x + 1$ ✓'], answerLatex: '2x - 1,\\; R = 3' },
    tags: ['long-division', 'verification'], source: 'CBSE 2022 Board',
  },
];

// ─── Pair of Linear Equations ───────────────────────────────
const linearEquations: Question[] = [
  {
    id: makeId('Pair of Linear Equations', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Graphical Method',
    subtopic: 'Consistent/Inconsistent', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'The pair of equations $x + y = 5$ and $x - y = 3$ has ______ (unique solution / no solution / infinitely many solutions).',
    solution: { steps: ['$\\frac{a_1}{a_2} = \\frac{1}{1} = 1$, $\\frac{b_1}{b_2} = \\frac{1}{-1} = -1$', 'Since $\\frac{a_1}{a_2} \\neq \\frac{b_1}{b_2}$, the lines intersect.', 'Unique solution.'], answerLatex: '\\text{Unique solution}' },
    tags: ['consistent', 'intersection'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Pair of Linear Equations', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Substitution Method',
    subtopic: 'Solving', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Solve: $2x + 3y = 11$ and $x + 2y = 7$.',
    solution: { steps: ['From equation 2: $x = 7 - 2y$.', 'Substitute in equation 1: $2(7 - 2y) + 3y = 11$', '$14 - 4y + 3y = 11$', '$-y = -3 \\Rightarrow y = 3$', '$x = 7 - 2(3) = 1$'], answerLatex: 'x = 1,\\; y = 3' },
    tags: ['substitution'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Pair of Linear Equations', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Word Problems',
    subtopic: 'Age Problems', difficulty: 'medium', marks: 3, estimatedMinutes: 6,
    questionLatex: 'The sum of digits of a two-digit number is $9$. If $27$ is added to the number, the digits get interchanged. Find the number.',
    solution: { steps: ['Let the number be $10a + b$.', 'Equation 1: $a + b = 9$', 'Equation 2: $10a + b + 27 = 10b + a$', '$9a - 9b = -27 \\Rightarrow a - b = -3$', 'Adding: $2a = 6 \\Rightarrow a = 3$, $b = 6$'], answerLatex: '36' },
    tags: ['word-problem', 'digit-problem'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Pair of Linear Equations', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Elimination Method',
    subtopic: 'Solving', difficulty: 'easy', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Solve using elimination: $x + y = 5$ and $2x - y = 1$.',
    solution: { steps: ['Adding the two equations: $3x = 6 \\Rightarrow x = 2$', 'Substitute: $2 + y = 5 \\Rightarrow y = 3$'], answerLatex: 'x = 2,\\; y = 3' },
    tags: ['elimination'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Pair of Linear Equations', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Substitution Method',
    subtopic: 'Solving', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Solve by substitution: $3x - y = 8$ and $x + 2y = 5$.',
    solution: { steps: ['From $x + 2y = 5$: $x = 5 - 2y$.', 'Substitute: $3(5 - 2y) - y = 8$', '$15 - 6y - y = 8 \\Rightarrow -7y = -7 \\Rightarrow y = 1$', '$x = 5 - 2(1) = 3$'], answerLatex: 'x = 3,\\; y = 1' },
    tags: ['substitution', 'solving'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Pair of Linear Equations', 6),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Word Problems',
    subtopic: 'Cost Problems', difficulty: 'medium', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Two pens and three erasers cost Rs 9, while four pens and one eraser cost Rs 13. Find the cost of one pen and one eraser.',
    solution: { steps: ['Let the cost of a pen be $p$ and an eraser be $e$ (in rupees).', 'Equation 1: $2p + 3e = 9$', 'Equation 2: $4p + e = 13$', 'From eq. 2: $e = 13 - 4p$. Substitute in eq. 1: $2p + 3(13 - 4p) = 9$', '$2p + 39 - 12p = 9 \\Rightarrow -10p = -30 \\Rightarrow p = 3$', '$e = 13 - 4(3) = 1$'], answerLatex: 'Pen: Rs 3,\\; eraser: Rs 1' },
    tags: ['word-problem', 'cost'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Pair of Linear Equations', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Consistency of Equations',
    subtopic: 'Infinite Solutions', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'For what value of $k$ do the equations $kx + 3y = k - 3$ and $12x + ky = k$ have infinitely many solutions?',
    solution: { steps: ['For infinitely many solutions: $\\frac{k}{12} = \\frac{3}{k} = \\frac{k - 3}{k}$', 'From $\\frac{k}{12} = \\frac{3}{k}$: $k^2 = 36 \\Rightarrow k = \\pm 6$', 'From $\\frac{3}{k} = \\frac{k - 3}{k}$: $3 = k - 3 \\Rightarrow k = 6$', 'Common value: $k = 6$'], answerLatex: 'k = 6' },
    tags: ['infinite-solutions', 'coefficient-comparison'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Pair of Linear Equations', 8),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Pair of Linear Equations in Two Variables', topic: 'Word Problems',
    subtopic: 'Fraction Problems', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'The numerator of a fraction is 4 less than its denominator. If 1 is added to both the numerator and the denominator, the fraction becomes $\\frac{2}{3}$. Find the original fraction.',
    solution: { steps: ['Let the fraction be $\\frac{x - 4}{x}$.', 'Adding 1 to both: $\\frac{x - 4 + 1}{x + 1} = \\frac{2}{3}$', '$\\frac{x - 3}{x + 1} = \\frac{2}{3}$', 'Cross-multiplying: $3(x - 3) = 2(x + 1)$', '$3x - 9 = 2x + 2 \\Rightarrow x = 11$', 'Fraction: $\\frac{11 - 4}{11} = \\frac{7}{11}$'], answerLatex: '\\frac{7}{11}' },
    tags: ['word-problem', 'fraction'], source: 'CBSE 2024 Sample',
  },
];

// ─── Quadratic Equations ────────────────────────────────────
const quadraticEquations: Question[] = [
  {
    id: makeId('Quadratic Equations', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Quadratic Equations', topic: 'Solving Quadratics',
    subtopic: 'Factoring', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Solve: $x^2 - 7x + 12 = 0$.',
    solution: { steps: ['$(x-3)(x-4) = 0$', '$x = 3$ or $x = 4$'], answerLatex: 'x = 3,\\; x = 4' },
    tags: ['factoring', 'quadratic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Quadratic Equations', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Nature of Roots',
    subtopic: 'Discriminant', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the discriminant of $2x^2 - 4x + 3 = 0$ and determine the nature of its roots.',
    solution: { steps: ['$a = 2, b = -4, c = 3$', '$\\Delta = b^2 - 4ac = 16 - 24 = -8$', 'Since $\\Delta < 0$, the roots are not real (complex conjugate).'], answerLatex: '\\Delta = -8,\\; \\text{no real roots}' },
    tags: ['discriminant', 'nature-of-roots'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Quadratic Equations', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Word Problems',
    subtopic: 'Area Problems', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'A rectangular garden is $80\\text{ m} \\times 60\\text{ m}$. A path of uniform width is built around the garden. If the area of the path is $2400\\text{ m}^2$, find the width of the path.',
    solution: { steps: ['Let width = $x$ m.', 'Outer dimensions: $(80+2x)(60+2x)$', 'Area of path: $(80+2x)(60+2x) - 4800 = 2400$', '$4800 + 280x + 4x^2 - 4800 = 2400$', '$4x^2 + 280x - 2400 = 0$', '$x^2 + 70x - 600 = 0$', '$(x+10)(x-60) = 0$', '$x = 10$ (since $x > 0$)'], answerLatex: '10\\text{ m}' },
    tags: ['word-problem', 'area', 'applied'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Quadratic Equations', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Quadratic Equations', topic: 'Solving Quadratics',
    subtopic: 'Quadratic Formula', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Solve $2x^2 + 3x - 5 = 0$ using the quadratic formula.',
    solution: { steps: ['$a=2, b=3, c=-5$', '$x = \\frac{-3 \\pm \\sqrt{9+40}}{4} = \\frac{-3 \\pm 7}{4}$', '$x = \\frac{4}{4} = 1$ or $x = \\frac{-10}{4} = -\\frac{5}{2}$'], answerLatex: 'x = 1 \\text{ or } x = -\\frac{5}{2}' },
    tags: ['quadratic-formula'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Quadratic Equations', 5),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Nature of Roots',
    subtopic: 'Finding k', difficulty: 'hard', marks: 3, estimatedMinutes: 5,
    questionLatex: 'For what values of $k$ does $x^2 + kx + 9 = 0$ have two equal real roots?',
    solution: { steps: ['For equal roots, $\\Delta = 0$.', '$k^2 - 4(1)(9) = 0$', '$k^2 = 36$', '$k = \\pm 6$'], answerLatex: 'k = 6 \\text{ or } k = -6' },
    tags: ['discriminant', 'equal-roots'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Quadratic Equations', 6),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Solving Quadratics',
    subtopic: 'Factoring', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Solve: $x^2 - 6x + 5 = 0$.',
    solution: { steps: ['$(x - 1)(x - 5) = 0$', '$x = 1$ or $x = 5$'], answerLatex: 'x = 1,\\; x = 5' },
    tags: ['factoring', 'quadratic'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Quadratic Equations', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Nature of Roots',
    subtopic: 'Finding k', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'For what value of $k$ does $2x^2 + kx + 3 = 0$ have equal roots?',
    solution: { steps: ['For equal roots, $\\Delta = 0$.', '$k^2 - 4(2)(3) = 0$', '$k^2 = 24$', '$k = \\pm 2\\sqrt{6}$'], answerLatex: 'k = 2\\sqrt{6} \\text{ or } k = -2\\sqrt{6}' },
    tags: ['discriminant', 'equal-roots', 'find-k'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Quadratic Equations', 8),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Word Problems',
    subtopic: 'Speed Problems', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less for the same journey. Find the speed of the train.',
    solution: { steps: ['Let the speed be $x$ km/h.', 'Time at speed $x$: $\\frac{360}{x}$ hours.', 'Time at speed $x + 5$: $\\frac{360}{x + 5}$ hours.', '$\\frac{360}{x} - \\frac{360}{x + 5} = 1$', '$\\frac{360(x + 5) - 360x}{x(x + 5)} = 1$', '$\\frac{1800}{x^2 + 5x} = 1$', '$x^2 + 5x - 1800 = 0$', '$(x + 45)(x - 40) = 0$', '$x = 40$ (speed cannot be negative)'], answerLatex: '40 \\text{ km/h}' },
    tags: ['word-problem', 'speed', 'applied'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Quadratic Equations', 9),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Quadratic Equations', topic: 'Word Problems',
    subtopic: 'Number Problems', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'The product of two consecutive positive integers is 306. Find the integers.',
    solution: { steps: ['Let the integers be $n$ and $n + 1$.', '$n(n + 1) = 306$', '$n^2 + n - 306 = 0$', '$(n + 18)(n - 17) = 0$', '$n = 17$ (since $n > 0$)', 'Integer pair: $17$ and $18$'], answerLatex: '17 \\text{ and } 18' },
    tags: ['word-problem', 'product', 'integers'], source: 'CBSE 2023 Board',
  },
];

// ─── Arithmetic Progressions ────────────────────────────────
const arithmeticProgressions: Question[] = [
  {
    id: makeId('Arithmetic Progressions', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Arithmetic Progressions', topic: 'Common Difference',
    subtopic: 'Finding d', difficulty: 'easy', marks: 1, estimatedMinutes: 1,
    questionLatex: 'Find the common difference of the AP: $3, 7, 11, 15, \\ldots$',
    solution: { steps: ['$d = 7 - 3 = 4$'], answerLatex: 'd = 4' },
    tags: ['common-difference', 'basic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Arithmetic Progressions', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Arithmetic Progressions', topic: 'nth Term',
    subtopic: 'Finding term', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the $10^{\\text{th}}$ term of the AP: $5, 8, 11, 14, \\ldots$',
    solution: { steps: ['$a = 5, d = 3$', '$a_{10} = a + 9d = 5 + 27 = 32$'], answerLatex: '32' },
    tags: ['nth-term'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Arithmetic Progressions', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Arithmetic Progressions', topic: 'Sum of n Terms',
    subtopic: 'Finding sum', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the sum of the first $20$ terms of the AP: $1, 4, 7, 10, \\ldots$',
    solution: { steps: ['$a = 1, d = 3, n = 20$', '$S_{20} = \\frac{20}{2}[2(1) + 19(3)] = 10[2 + 57] = 10 \\times 59 = 590$'], answerLatex: 'S_{20} = 590' },
    tags: ['sum', 'ap'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Arithmetic Progressions', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Arithmetic Progressions', topic: 'Word Problems',
    subtopic: 'Applied', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'A man starts a job with a salary of ₹$10{,}000$ and gets an annual increment of ₹$800$. In which year will his salary be ₹$15{,}200$?',
    solution: { steps: ['$a = 10000, d = 800, a_n = 15200$', '$15200 = 10000 + (n-1)(800)$', '$5200 = 800(n-1)$', '$n - 1 = 6.5 \\Rightarrow n = 7.5$', 'Since $n$ must be an integer, his salary exceeds $15200$ in the $8^{\\text{th}}$ year.'], answerLatex: '8^{\\text{th}} \\text{ year}' },
    tags: ['word-problem', 'applied', 'salary'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Arithmetic Progressions', 5),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Arithmetic Progressions', topic: 'nth Term',
    subtopic: 'Negative common difference', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the $10^{\\text{th}}$ term of the AP: $9, 3, -3, -9, \\ldots$',
    solution: { steps: ['$a = 9, d = 3 - 9 = -6$', '$a_{10} = a + 9d = 9 + 9(-6) = 9 - 54 = -45$'], answerLatex: '-45' },
    tags: ['nth-term', 'negative-d'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Arithmetic Progressions', 6),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Arithmetic Progressions', topic: 'nth Term',
    subtopic: 'Finding n', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Which term of the AP $2, 5, 8, \\ldots$ is $32$?',
    solution: { steps: ['$a = 2, d = 3$', '$a_n = a + (n-1)d = 32$', '$2 + (n-1)(3) = 32$', '$3(n-1) = 30$', '$n - 1 = 10$', '$n = 11$'], answerLatex: '11^{\\text{th}} \\text{ term}' },
    tags: ['nth-term', 'find-n'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Arithmetic Progressions', 7),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Arithmetic Progressions', topic: 'nth Term',
    subtopic: 'Negative common difference', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the $11^{\\text{th}}$ term of the AP: $8, 4, 0, -4, \\ldots$',
    solution: { steps: ['$a = 8, d = 4 - 8 = -4$', '$a_{11} = a + 10d = 8 + 10(-4) = 8 - 40 = -32$'], answerLatex: '-32' },
    tags: ['nth-term', 'negative-d'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Arithmetic Progressions', 8),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Arithmetic Progressions', topic: 'nth Term',
    subtopic: 'Finding a and d', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'The $4^{\\text{th}}$ term of an AP is $22$ and the $8^{\\text{th}}$ term is $46$. Find the first term and the common difference.',
    solution: { steps: ['$a + 3d = 22$', '$a + 7d = 46$', 'Subtracting: $4d = 24 \\Rightarrow d = 6$', '$a + 18 = 22 \\Rightarrow a = 4$'], answerLatex: 'a = 4,\\; d = 6' },
    tags: ['nth-term', 'find-a-d'], source: 'CBSE 2023 Board',
  },
];

// ─── Triangles ──────────────────────────────────────────────
const triangles: Question[] = [
  {
    id: makeId('Triangles', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Triangles', topic: 'Similarity',
    subtopic: 'AA Similarity', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'In $\\triangle ABC$, $D$ and $E$ are points on $AB$ and $AC$ such that $DE \\parallel BC$. If $AD = 3$, $DB = 2$, find the ratio $\\frac{AD}{AB}$.',
    solution: { steps: ['$AB = AD + DB = 3 + 2 = 5$', '$\\frac{AD}{AB} = \\frac{3}{5}$'], answerLatex: '\\frac{3}{5}' },
    tags: ['similarity', 'parallel'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Triangles', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Triangles', topic: 'Similarity',
    subtopic: 'Ratios', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'In $\\triangle ABC$, $DE \\parallel BC$ where $D \\in AB$ and $E \\in AC$. If $AD = 3$ cm, $DB = 2$ cm, and $DE = 4$ cm, find $BC$.',
    solution: { steps: ['Since $DE \\parallel BC$, $\\triangle ADE \\sim \\triangle ABC$ (AA).', '$\\frac{AD}{AB} = \\frac{DE}{BC}$', '$\\frac{3}{5} = \\frac{4}{BC}$', '$BC = \\frac{20}{3}$ cm'], answerLatex: 'BC = \\frac{20}{3} \\text{ cm}' },
    tags: ['similarity', 'ratio'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Triangles', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Triangles', topic: 'Areas of Similar Triangles',
    subtopic: 'Area ratio', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'If $\\triangle ABC \\sim \\triangle PQR$ and $\\frac{AB}{PQ} = \\frac{2}{3}$, find the ratio of the areas of $\\triangle ABC$ and $\\triangle PQR$.',
    solution: { steps: ['Ratio of areas of similar triangles = square of ratio of corresponding sides.', '$\\frac{\\text{Area}(ABC)}{\\text{Area}(PQR)} = \\left(\\frac{AB}{PQ}\\right)^2 = \\left(\\frac{2}{3}\\right)^2 = \\frac{4}{9}$'], answerLatex: '4 : 9' },
    tags: ['area-ratio', 'similarity'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Triangles', 4),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Triangles', topic: 'Pythagoras Theorem',
    subtopic: 'Right Triangle', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'A right triangle has legs $9$ cm and $12$ cm. Find the length of the hypotenuse.',
    solution: { steps: ['$c = \\sqrt{9^2 + 12^2} = \\sqrt{81 + 144} = \\sqrt{225} = 15$'], answerLatex: '15 \\text{ cm}' },
    tags: ['pythagoras', 'hypotenuse'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Triangles', 5),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Triangles', topic: 'Basic Proportionality Theorem',
    subtopic: 'Converse', difficulty: 'easy', marks: 2, estimatedMinutes: 3,
    questionLatex: 'In $\\triangle ABC$, $D$ and $E$ are points on $AB$ and $AC$ respectively such that $\\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{1}{2}$. Show that $DE \\parallel BC$.',
    solution: { steps: ['$\\frac{AD}{DB} = \\frac{AE}{EC} = \\frac{1}{2}$', 'By the converse of the Basic Proportionality Theorem, if a line divides two sides of a triangle in the same ratio, it is parallel to the third side.', 'Hence $DE \\parallel BC$.'], answerLatex: 'DE \\parallel BC \\text{ (by converse of BPT)}' },
    tags: ['bpt', 'converse', 'parallel'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Triangles', 6),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Triangles', topic: 'Areas of Similar Triangles',
    subtopic: 'Side ratio from area ratio', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'If $\\triangle ABC \\sim \\triangle PQR$ and the ratio of their areas is $121 : 64$, find the ratio of the corresponding sides.',
    solution: { steps: ['Ratio of areas of similar triangles = square of the ratio of corresponding sides.', '$\\left(\\frac{AB}{PQ}\\right)^2 = \\frac{121}{64}$', '$\\frac{AB}{PQ} = \\sqrt{\\frac{121}{64}} = \\frac{11}{8}$'], answerLatex: '11 : 8' },
    tags: ['area-ratio', 'side-ratio'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Triangles', 7),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Triangles', topic: 'Pythagoras Theorem',
    subtopic: 'Ladder problem', difficulty: 'easy', marks: 2, estimatedMinutes: 3,
    questionLatex: 'A ladder $13$ m long is placed against a wall such that its foot is $5$ m away from the wall. Find the height of the window it reaches.',
    solution: { steps: ['Let height be $h$.', '$h^2 + 5^2 = 13^2$ (Pythagoras)', '$h^2 = 169 - 25 = 144$', '$h = 12$ m'], answerLatex: '12 \\text{ m}' },
    tags: ['pythagoras', 'ladder'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Triangles', 8),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Triangles', topic: 'Pythagoras Theorem',
    subtopic: 'Altitude to hypotenuse', difficulty: 'hard', marks: 3, estimatedMinutes: 5,
    questionLatex: 'In a right triangle $ABC$, right angled at $B$, $BD \\perp AC$. If $AD = 4$ cm and $DC = 9$ cm, find $BD$.',
    solution: { steps: ['In a right triangle, the altitude to the hypotenuse gives $BD^2 = AD \\times DC$.', '$BD^2 = 4 \\times 9 = 36$', '$BD = 6$ cm'], answerLatex: 'BD = 6 \\text{ cm}' },
    tags: ['pythagoras', 'altitude', 'geometric-mean'], source: 'CBSE 2022 Board',
  },
];

// ─── Coordinate Geometry ────────────────────────────────────
const coordinateGeometry: Question[] = [
  {
    id: makeId('Coordinate Geometry', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Coordinate Geometry', topic: 'Distance Formula',
    subtopic: 'Distance', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the distance between the points $(1, 2)$ and $(4, 6)$.',
    solution: { steps: ['$d = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5$'], answerLatex: '5' },
    tags: ['distance', 'basic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Coordinate Geometry', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Coordinate Geometry', topic: 'Section Formula',
    subtopic: 'Internal Division', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the coordinates of the point which divides the line segment joining $(-1, 7)$ and $(4, -3)$ in the ratio $2 : 3$ internally.',
    solution: { steps: ['$\\left(\\frac{2(4)+3(-1)}{2+3}, \\frac{2(-3)+3(7)}{2+3}\\right)$', '$= \\left(\\frac{5}{5}, \\frac{15}{5}\\right) = (1, 3)$'], answerLatex: '(1, 3)' },
    tags: ['section-formula', 'internal'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Coordinate Geometry', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Coordinate Geometry', topic: 'Section Formula',
    subtopic: 'Ratio from midpoint', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the ratio in which the point $(2, -4)$ divides the line segment joining $(3, 1)$ and $(-3, 7)$.',
    solution: { steps: ['Let ratio be $k : 1$.', '$\\frac{k(-3) + 1(3)}{k+1} = 2 \\Rightarrow -3k + 3 = 2k + 2 \\Rightarrow k = \\frac{1}{5}$'], answerLatex: '1 : 5' },
    tags: ['section-formula', 'reverse'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Coordinate Geometry', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Coordinate Geometry', topic: 'Distance Formula',
    subtopic: 'Equidistant', difficulty: 'hard', marks: 3, estimatedMinutes: 5,
    questionLatex: 'If the point $P(x, y)$ is equidistant from $A(5, 1)$ and $B(-1, 5)$, prove that $3x = 2y$.',
    solution: { steps: ['$PA = PB \\Rightarrow PA^2 = PB^2$', '$(x-5)^2 + (y-1)^2 = (x+1)^2 + (y-5)^2$', '$x^2 - 10x + 25 + y^2 - 2y + 1 = x^2 + 2x + 1 + y^2 - 10y + 25$', '$-12x + 8y = 0$', '$3x = 2y$ ✓'], answerLatex: '3x = 2y' },
    tags: ['equidistant', 'proof'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Coordinate Geometry', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Coordinate Geometry', topic: 'Section Formula',
    subtopic: 'Midpoint', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the midpoint of the line segment joining the points $(-3, 5)$ and $(1, -7)$.',
    solution: { steps: ['$M = \\left(\\frac{-3 + 1}{2}, \\frac{5 + (-7)}{2}\\right)$', '$= \\left(\\frac{-2}{2}, \\frac{-2}{2}\\right) = (-1, -1)$'], answerLatex: '(-1, -1)' },
    tags: ['midpoint', 'basic'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Coordinate Geometry', 6),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Coordinate Geometry', topic: 'Section Formula',
    subtopic: 'Midpoint as centre', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'If $(-1, 2)$ and $(7, 2)$ are the endpoints of the diameter of a circle, find the centre of the circle.',
    solution: { steps: ['The centre of a circle is the midpoint of its diameter.', '$C = \\left(\\frac{-1 + 7}{2}, \\frac{2 + 2}{2}\\right) = (3, 2)$'], answerLatex: '(3, 2)' },
    tags: ['midpoint', 'circle'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Coordinate Geometry', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Coordinate Geometry', topic: 'Collinearity',
    subtopic: 'Slope comparison', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Show that the points $A(-2, -3)$, $B(1, 0)$ and $C(4, 3)$ are collinear.',
    solution: { steps: ['Slope of $AB = \\frac{0 - (-3)}{1 - (-2)} = \\frac{3}{3} = 1$', 'Slope of $BC = \\frac{3 - 0}{4 - 1} = \\frac{3}{3} = 1$', 'Since the slopes are equal, the three points are collinear.'], answerLatex: 'A, B and C are collinear' },
    tags: ['collinear', 'slope'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Coordinate Geometry', 8),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Coordinate Geometry', topic: 'Distance Formula',
    subtopic: 'Equidistant on axis', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the point on the $y$-axis which is equidistant from the points $(2, 5)$ and $(-2, 13)$.',
    solution: { steps: ['A point on the $y$-axis has coordinates $(0, y)$.', '$(0-2)^2 + (y-5)^2 = (0+2)^2 + (y-13)^2$', '$4 + y^2 - 10y + 25 = 4 + y^2 - 26y + 169$', '$16y = 144 \\Rightarrow y = 9$'], answerLatex: '(0, 9)' },
    tags: ['equidistant', 'axis'], source: 'CBSE 2022 Board',
  },
];

// ─── Introduction to Trigonometry ───────────────────────────
const trigonometry: Question[] = [
  {
    id: makeId('Introduction to Trigonometry', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Introduction to Trigonometry', topic: 'Trigonometric Ratios',
    subtopic: 'Basic', difficulty: 'easy', marks: 1, estimatedMinutes: 1,
    questionLatex: 'If $\\sin \\theta = \\frac{3}{5}$, find $\\cos \\theta$.',
    solution: { steps: ['$\\cos \\theta = \\sqrt{1 - \\sin^2 \\theta} = \\sqrt{1 - \\frac{9}{25}} = \\frac{4}{5}$'], answerLatex: '\\cos \\theta = \\frac{4}{5}' },
    tags: ['basic', 'sine-cosine'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Introduction to Trigonometry', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Identities',
    subtopic: 'Fundamental Identity', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'If $\\sin \\theta = \\frac{3}{5}$, find the value of $\\cos \\theta$ and $\\tan \\theta$, where $\\theta$ is an acute angle.',
    solution: { steps: ['$\\cos^2 \\theta = 1 - \\frac{9}{25} = \\frac{16}{25}$', '$\\cos \\theta = \\frac{4}{5}$ (positive for acute)', '$\\tan \\theta = \\frac{3/5}{4/5} = \\frac{3}{4}$'], answerLatex: '\\cos \\theta = \\frac{4}{5},\\; \\tan \\theta = \\frac{3}{4}' },
    tags: ['identities', 'acute'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Introduction to Trigonometry', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Trigonometric Ratios',
    subtopic: 'Evaluation', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Evaluate: $\\sin 30^\\circ \\cos 60^\\circ + \\tan 45^\\circ$.',
    solution: { steps: ['$\\sin 30^\\circ = \\frac{1}{2}, \\cos 60^\\circ = \\frac{1}{2}, \\tan 45^\\circ = 1$', '$= \\frac{1}{2} \\cdot \\frac{1}{2} + 1 = \\frac{1}{4} + 1 = \\frac{5}{4}$'], answerLatex: '\\frac{5}{4}' },
    tags: ['evaluation', 'standard-angles'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Introduction to Trigonometry', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Introduction to Trigonometry', topic: 'Identities',
    subtopic: 'Proof', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Prove that $(\\sin \\theta + \\csc \\theta)^2 + (\\cos \\theta + \\sec \\theta)^2 = 7 + \\tan^2 \\theta + \\cot^2 \\theta$.',
    solution: { steps: ['LHS: $\\sin^2\\theta + 2\\sin\\theta\\csc\\theta + \\csc^2\\theta + \\cos^2\\theta + 2\\cos\\theta\\sec\\theta + \\sec^2\\theta$', '$= 1 + 2(1) + (1 + \\cot^2\\theta) + 2(1) + (1 + \\tan^2\\theta)$', '$= 1 + 2 + 1 + \\cot^2\\theta + 2 + 1 + \\tan^2\\theta$', '$= 7 + \\tan^2\\theta + \\cot^2\\theta = $ RHS ✓'], answerLatex: '\\text{Proven}' },
    tags: ['proof', 'identity'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Introduction to Trigonometry', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Trigonometric Ratios',
    subtopic: 'Compound angles', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the value of $\\sin 75^\\circ$.',
    solution: { steps: ['$\\sin 75^\\circ = \\sin(45^\\circ + 30^\\circ)$', '$= \\sin 45^\\circ \\cos 30^\\circ + \\cos 45^\\circ \\sin 30^\\circ$', '$= \\frac{1}{\\sqrt{2}} \\cdot \\frac{\\sqrt{3}}{2} + \\frac{1}{\\sqrt{2}} \\cdot \\frac{1}{2} = \\frac{\\sqrt{3} + 1}{2\\sqrt{2}}$'], answerLatex: '\\frac{\\sqrt{3} + 1}{2\\sqrt{2}}' },
    tags: ['compound-angles', 'evaluation'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Introduction to Trigonometry', 6),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Identities',
    subtopic: 'Proof', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Prove that $(\\sec \\theta - \\tan \\theta)(\\sec \\theta + \\tan \\theta) = 1$.',
    solution: { steps: ['LHS: $\\sec^2 \\theta - \\tan^2 \\theta$', 'Using $\\sec^2 \\theta = 1 + \\tan^2 \\theta$: $1 + \\tan^2 \\theta - \\tan^2 \\theta = 1$', '$= $ RHS ✓'], answerLatex: '\\text{Proven}' },
    tags: ['proof', 'identity'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Introduction to Trigonometry', 7),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Identities',
    subtopic: 'Application', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'If $\\sec \\theta - \\tan \\theta = \\frac{1}{7}$, find the value of $\\sec \\theta + \\tan \\theta$.',
    solution: { steps: ['$(\\sec \\theta - \\tan \\theta)(\\sec \\theta + \\tan \\theta) = \\sec^2 \\theta - \\tan^2 \\theta = 1$', '$\\frac{1}{7} (\\sec \\theta + \\tan \\theta) = 1$', '$\\sec \\theta + \\tan \\theta = 7$'], answerLatex: '7' },
    tags: ['identity', 'application'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Introduction to Trigonometry', 8),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Introduction to Trigonometry', topic: 'Identities',
    subtopic: 'Proof', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Prove that $\\sec^2 \\theta + \\csc^2 \\theta = \\sec^2 \\theta \\csc^2 \\theta$.',
    solution: { steps: ['LHS: $\\frac{1}{\\cos^2\\theta} + \\frac{1}{\\sin^2\\theta} = \\frac{\\sin^2\\theta + \\cos^2\\theta}{\\sin^2\\theta \\cos^2\\theta}$', 'Using $\\sin^2\\theta + \\cos^2\\theta = 1$: $= \\frac{1}{\\sin^2\\theta \\cos^2\\theta}$', '$= \\csc^2\\theta \\cdot \\sec^2\\theta = \\sec^2\\theta \\csc^2\\theta = $ RHS ✓'], answerLatex: '\\text{Proven}' },
    tags: ['proof', 'identity'], source: 'CBSE 2023 Board',
  },
];

// ─── Some Applications of Trigonometry ──────────────────────
const trigApplications: Question[] = [
  {
    id: makeId('Some Applications of Trigonometry', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Angle of Elevation', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'The angle of elevation of the top of a tower from a point on the ground is $30^\\circ$. If the point is $20$ m away from the foot of the tower, find the height of the tower.',
    solution: { steps: ['Let height of tower be $h$ m.', '$\\tan 30^\\circ = \\frac{h}{20}$', '$\\frac{1}{\\sqrt{3}} = \\frac{h}{20}$', '$h = \\frac{20}{\\sqrt{3}}$ m'], answerLatex: '\\frac{20}{\\sqrt{3}} \\text{ m}' },
    tags: ['heights', 'elevation'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Some Applications of Trigonometry', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Angle of Depression', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'From the top of a cliff $60$ m high, the angle of depression of a boat is $45^\\circ$. How far is the boat from the foot of the cliff?',
    solution: { steps: ['Let distance of boat from foot be $x$ m.', 'Angle of depression $= 45^\\circ$ means the angle of elevation from the boat is also $45^\\circ$.', '$\\tan 45^\\circ = \\frac{60}{x}$', '$1 = \\frac{60}{x} \\Rightarrow x = 60$ m'], answerLatex: '60 \\text{ m}' },
    tags: ['depression', 'heights'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Some Applications of Trigonometry', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Two Positions', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'A kite is flying at a height of $60$ m above the ground. The string attached to the kite is temporarily tied to a point on the ground. The inclination of the string with the ground is $60^\\circ$. Find the length of the string, assuming there is no slack in the string.',
    solution: { steps: ['Let length of string be $L$ m.', '$\\sin 60^\\circ = \\frac{60}{L}$', '$\\frac{\\sqrt{3}}{2} = \\frac{60}{L}$', '$L = \\frac{120}{\\sqrt{3}} = 40\\sqrt{3}$ m'], answerLatex: '40\\sqrt{3} \\text{ m}' },
    tags: ['kite', 'heights'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Some Applications of Trigonometry', 4),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Angle of Elevation', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'A tree breaks due to a storm and the broken part bends so that the top of the tree touches the ground making an angle of $30^\\circ$ with the ground. The distance between the foot of the tree and the top touching the ground is $10$ m. Find the height of the tree.',
    solution: { steps: ['Let the height of the uncut (upright) part be $h_1$ and the bent part be $h_2$.', '$\u03b8 = 30^\\circ$, adjacent $= 10$ m.', '$\\tan 30^\\circ = \\frac{h_1}{10} \\Rightarrow h_1 = \\frac{10}{\\sqrt{3}}$ m', '$\\cos 30^\\circ = \\frac{10}{h_2} \\Rightarrow h_2 = \\frac{20}{\\sqrt{3}}$ m', 'Total height $= h_1 + h_2 = \\frac{10}{\\sqrt{3}} + \\frac{20}{\\sqrt{3}} = \\frac{30}{\\sqrt{3}} = 10\\sqrt{3}$ m'], answerLatex: '10\\sqrt{3} \\text{ m}' },
    tags: ['tree', 'heights', 'applied'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Some Applications of Trigonometry', 5),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Flagstaff on Tower', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'A vertical flagstaff stands on a tower $20$ m high. From a point on the ground, the angles of elevation of the top and bottom of the flagstaff are $60^\\circ$ and $45^\\circ$. Find the height of the flagstaff.',
    solution: { steps: ['Let height of flagstaff be $h$ m and the point be $d$ m from the tower.', '$\\tan 45^\\circ = \\frac{20}{d} \\Rightarrow d = 20$ m', '$\\tan 60^\\circ = \\frac{20 + h}{20} \\Rightarrow 20 + h = 20\\sqrt{3}$', '$h = 20(\\sqrt{3} - 1)$ m'], answerLatex: '20(\\sqrt{3} - 1) \\text{ m}' },
    tags: ['flagstaff', 'two-angles'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Some Applications of Trigonometry', 6),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Elevation and Depression', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'From the top of a building $7$ m high, the angle of elevation of the top of a cable tower is $60^\\circ$ and the angle of depression of its foot is $45^\\circ$. Find the height of the cable tower.',
    solution: { steps: ['Let height of cable tower be $H$ m and horizontal distance be $d$ m.', '$\\tan 45^\\circ = \\frac{7}{d} \\Rightarrow d = 7$ m', '$\\tan 60^\\circ = \\frac{H - 7}{7} \\Rightarrow H - 7 = 7\\sqrt{3}$', '$H = 7(1 + \\sqrt{3})$ m'], answerLatex: '7(\\sqrt{3} + 1) \\text{ m}' },
    tags: ['cable-tower', 'elevation-depression'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Some Applications of Trigonometry', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Mutual Elevation', difficulty: 'medium', marks: 3, estimatedMinutes: 6,
    questionLatex: 'The angle of elevation of the top of a building from the foot of a tower is $30^\\circ$, and the angle of elevation of the top of the tower from the foot of the building is $60^\\circ$. If the tower is $50$ m high, find the height of the building.',
    solution: { steps: ['Let height of building be $x$ m and distance between them be $d$ m.', '$\\tan 60^\\circ = \\frac{50}{d} \\Rightarrow d = \\frac{50}{\\sqrt{3}}$ m', '$\\tan 30^\\circ = \\frac{x}{d} \\Rightarrow \\frac{1}{\\sqrt{3}} = \\frac{x \\sqrt{3}}{50}$', '$x = \\frac{50}{3}$ m'], answerLatex: '\\frac{50}{3} \\text{ m}' },
    tags: ['mutual-elevation', 'building'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Some Applications of Trigonometry', 8),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Some Applications of Trigonometry', topic: 'Heights and Distances',
    subtopic: 'Flagstaff on Tower', difficulty: 'hard', marks: 3, estimatedMinutes: 5,
    questionLatex: 'A flagstaff stands on a tower. From a point on the ground $30$ m away from the foot of the tower, the angles of elevation of the top and bottom of the flagstaff are $60^\\circ$ and $45^\\circ$. Find the height of the flagstaff.',
    solution: { steps: ['Let height of flagstaff be $h$ m and height of tower be $t$ m.', '$\\tan 45^\\circ = \\frac{t}{30} \\Rightarrow t = 30$ m', '$\\tan 60^\\circ = \\frac{30 + h}{30} \\Rightarrow 30 + h = 30\\sqrt{3}$', '$h = 30(\\sqrt{3} - 1)$ m'], answerLatex: '30(\\sqrt{3} - 1) \\text{ m}' },
    tags: ['flagstaff', 'two-angles', 'applied'], source: 'CBSE 2022 Board',
  },
];

// ─── Statistics ─────────────────────────────────────────────
const statistics: Question[] = [
  {
    id: makeId('Statistics', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Statistics', topic: 'Mean',
    subtopic: 'Direct Method', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the mean of $4, 7, 11, 15, 18$.',
    solution: { steps: ['$\\bar{x} = \\frac{4+7+11+15+18}{5} = \\frac{55}{5} = 11$'], answerLatex: '11' },
    tags: ['mean', 'basic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Statistics', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Statistics', topic: 'Median',
    subtopic: 'Ungrouped Data', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the median of $5, 2, 9, 1, 7, 6, 4$.',
    solution: { steps: ['Sorted: $1, 2, 4, 5, 6, 7, 9$ (n = 7)', 'Median = $4^{\\text{th}}$ term = $5$'], answerLatex: '5' },
    tags: ['median', 'ungrouped'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Statistics', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Statistics', topic: 'Mode',
    subtopic: 'Grouped Data', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the mode of the following distribution:\n\n| Class | $0-10$ | $10-20$ | $20-30$ | $30-40$ |\n|-------|--------|---------|---------|----------|\n| Freq | 5 | 8 | 12 | 3 |',
    solution: { steps: ['Modal class = $20-30$ (highest frequency = 12)', '$l = 20, f_1 = 12, f_0 = 8, f_2 = 3, h = 10$', 'Mode $= 20 + \\frac{12-8}{2(12)-8-3} \\times 10 = 20 + \\frac{4}{13} \\times 10 = 20 + 3.08 = 23.08$'], answerLatex: '\\text{Mode} \\approx 23.08' },
    tags: ['mode', 'grouped'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Statistics', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Statistics', topic: 'Mean',
    subtopic: 'Step Deviation', difficulty: 'hard', marks: 4, estimatedMinutes: 8,
    questionLatex: 'Find the mean using the step deviation method:\n\n| Class | $0-10$ | $10-20$ | $20-30$ | $30-40$ | $40-50$ |\n|-------|--------|---------|---------|---------|---------|\n| Freq | 5 | 8 | 12 | 10 | 5 |',
    solution: { steps: ['Assumed mean $a = 25$, $h = 10$', '$u_i = \\frac{x_i - 25}{10}$: $-2, -1, 0, 1, 2$', '$f_i u_i$: $-10, -8, 0, 10, 10$', '$\\sum f_i = 40$, $\\sum f_i u_i = 2$', 'Mean $= 25 + \\frac{2}{40} \\times 10 = 25.5$'], answerLatex: '25.5' },
    tags: ['step-deviation', 'mean'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Statistics', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Statistics', topic: 'Mean',
    subtopic: 'Ungrouped Data', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the mean of $18, 21, 24, 27$.',
    solution: { steps: ['$\\bar{x} = \\frac{18 + 21 + 24 + 27}{4} = \\frac{90}{4} = 22.5$'], answerLatex: '22.5' },
    tags: ['mean', 'ungrouped'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Statistics', 6),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Statistics', topic: 'Mean',
    subtopic: 'Grouped Data', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the mean of the following distribution:\n\n| Class | $0-10$ | $10-20$ | $20-30$ | $30-40$ | $40-50$ |\n|-------|--------|---------|---------|---------|---------|\n| Freq | 4 | 9 | 7 | 5 | 3 |',
    solution: { steps: ['Class marks: $5, 15, 25, 35, 45$', '$f_i x_i$: $20, 135, 175, 175, 135$', '$\\sum f_i = 28$, $\\sum f_i x_i = 640$', 'Mean $= \\frac{640}{28} = 22.857 \\approx 22.86$'], answerLatex: '\\approx 22.86' },
    tags: ['mean', 'grouped', 'direct-method'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Statistics', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Statistics', topic: 'Median',
    subtopic: 'Ungrouped Data', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the median of $3, 9, 6, 15, 12, 9, 10$.',
    solution: { steps: ['Sorted: $3, 6, 9, 9, 10, 12, 15$ (n = 7)', 'Median = $4^{\\text{th}}$ term = $9$'], answerLatex: '9' },
    tags: ['median', 'ungrouped'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Statistics', 8),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Statistics', topic: 'Mode',
    subtopic: 'Ungrouped Data', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the mode of $3, 8, 6, 8, 5, 8, 4$.',
    solution: { steps: ['The value $8$ occurs most frequently (3 times).'], answerLatex: '8' },
    tags: ['mode', 'ungrouped'], source: 'CBSE 2024 Sample',
  },
];

// ─── Probability ────────────────────────────────────────────
const probability: Question[] = [
  {
    id: makeId('Probability', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Probability', topic: 'Basic Probability',
    subtopic: 'Cards', difficulty: 'easy', marks: 1, estimatedMinutes: 1,
    questionLatex: 'A card is drawn from a well-shuffled deck of $52$ cards. Find the probability of getting a king.',
    solution: { steps: ['$P(\\text{king}) = \\frac{4}{52} = \\frac{1}{13}$'], answerLatex: '\\frac{1}{13}' },
    tags: ['cards', 'basic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Probability', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Probability', topic: 'Basic Probability',
    subtopic: 'Dice', difficulty: 'easy', marks: 1, estimatedMinutes: 1,
    questionLatex: 'Two dice are thrown simultaneously. Find the probability of getting a sum of $7$.',
    solution: { steps: ['Total outcomes = $6 \\times 6 = 36$', 'Favorable: $(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)$ — 6 outcomes', '$P = \\frac{6}{36} = \\frac{1}{6}$'], answerLatex: '\\frac{1}{6}' },
    tags: ['dice', 'sum'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Probability', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Probability', topic: 'Complementary Events',
    subtopic: 'Complement', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'A bag contains $5$ red balls and $3$ blue balls. If one ball is drawn at random, find the probability that it is NOT red.',
    solution: { steps: ['Total = $5 + 3 = 8$', '$P(\\text{not red}) = 1 - P(\\text{red}) = 1 - \\frac{5}{8} = \\frac{3}{8}$'], answerLatex: '\\frac{3}{8}' },
    tags: ['complement', 'bag'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Probability', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Probability', topic: 'Conditional Probability',
    subtopic: 'With replacement', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'A bag contains $3$ red and $2$ black balls. Two balls are drawn at random WITH replacement. Find the probability that both are red.',
    solution: { steps: ['$P(\\text{red on 1st draw}) = \\frac{3}{5}$', 'With replacement, $P(\\text{red on 2nd draw}) = \\frac{3}{5}$', '$P(\\text{both red}) = \\frac{3}{5} \\times \\frac{3}{5} = \\frac{9}{25}$'], answerLatex: '\\frac{9}{25}' },
    tags: ['with-replacement', 'independent'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Probability', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Probability', topic: 'Basic Probability',
    subtopic: 'Cards', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'A card is drawn at random from a well-shuffled deck of $52$ cards. Find the probability that it is a king or a queen.',
    solution: { steps: ['Total outcomes = $52$', 'Favourable outcomes = $4 + 4 = 8$', '$P = \\frac{8}{52} = \\frac{2}{13}$'], answerLatex: '\\frac{2}{13}' },
    tags: ['cards', 'king-queen'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Probability', 6),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Probability', topic: 'Basic Probability',
    subtopic: 'Balls', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'A bag contains $3$ red, $4$ blue and $3$ green balls. One ball is drawn at random. Find the probability that it is green.',
    solution: { steps: ['Total balls = $3 + 4 + 3 = 10$', 'Green balls = $3$', '$P = \\frac{3}{10}$'], answerLatex: '\\frac{3}{10}' },
    tags: ['bag', 'balls'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Probability', 7),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Probability', topic: 'Two Dice',
    subtopic: 'Sum', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Two dice are thrown together. Find the probability that the sum of the numbers on the two dice is a prime number.',
    solution: { steps: ['Total outcomes = $36$', 'Prime sums: $2, 3, 5, 7, 11$', 'Favourable outcomes = $1 + 2 + 4 + 6 + 2 = 15$', '$P = \\frac{15}{36} = \\frac{5}{12}$'], answerLatex: '\\frac{5}{12}' },
    tags: ['two-dice', 'prime-sum'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Probability', 8),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Probability', topic: 'Coins',
    subtopic: 'Two coins', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Two coins are tossed together. Find the probability of getting at least one head.',
    solution: { steps: ['Sample space: $HH, HT, TH, TT$', 'Favourable (at least one head): $HH, HT, TH$', '$P = \\frac{3}{4}$'], answerLatex: '\\frac{3}{4}' },
    tags: ['coins', 'at-least-one'], source: 'CBSE 2022 Board',
  },
];

// ─── Circles ────────────────────────────────────────────────
const circles: Question[] = [
  {
    id: makeId('Circles', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Circles', topic: 'Tangent Properties',
    subtopic: 'Perpendicularity', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'A tangent to a circle intersects it in ______ point(s).',
    solution: { steps: ['A tangent touches the circle at exactly one point.'], answerLatex: '1' },
    tags: ['tangent', 'basic'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Circles', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Circles', topic: 'Tangent from External Point',
    subtopic: 'Equal tangents', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'From an external point $P$, two tangents $PA$ and $PB$ are drawn to a circle with centre $O$. If $\\angle APB = 60^\\circ$, find $\\angle OAB$.',
    solution: { steps: ['Tangents from external point: $PA = PB$, $\\angle OAP = \\angle OBP = 90^\\circ$.', 'In quadrilateral $OAPB$: $\\angle AOB = 180^\\circ - 60^\\circ = 120^\\circ$.', 'In $\\triangle OAB$: $OA = OB$ (radii), so $\\triangle OAB$ is isosceles.', '$\\angle OAB = \\frac{180^\\circ - 120^\\circ}{2} = 30^\\circ$'], answerLatex: '30^\\circ' },
    tags: ['tangent', 'external-point'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Circles', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Circles', topic: 'Angle Properties',
    subtopic: 'Angle in semicircle', difficulty: 'easy', marks: 1, estimatedMinutes: 1,
    questionLatex: 'An angle inscribed in a semicircle is a ______.',
    solution: { steps: ['The angle in a semicircle is always $90^\\circ$ (right angle).'], answerLatex: '\\text{right angle}' },
    tags: ['semicircle', 'basic'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Circles', 4),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Circles', topic: 'Tangent Properties',
    subtopic: 'Two tangents meeting', difficulty: 'medium', marks: 3, estimatedMinutes: 5,
    questionLatex: 'A chord $PQ$ of length $8$ cm is drawn in a circle of radius $5$ cm. The tangents at $P$ and $Q$ meet at $T$. Find the length of $TP$.',
    solution: { steps: ['$PM = \\frac{8}{2} = 4$ cm (perpendicular from centre bisects chord)', '$OM = \\sqrt{5^2 - 4^2} = 3$ cm', 'For two tangents from $T$: $OP^2 = OM \\times OT$, so $5^2 = 3 \\times OT \\Rightarrow OT = \\frac{25}{3}$', '$TP = \\sqrt{OT^2 - OP^2} = \\sqrt{\\frac{625}{9} - 25} = \\sqrt{\\frac{400}{9}} = \\frac{20}{3}$ cm'], answerLatex: '\\frac{20}{3} \\text{ cm}' },
    tags: ['chord', 'tangents', 'length'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Circles', 5),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Circles', topic: 'Tangent Properties',
    subtopic: 'Tangent perpendicular to radius', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Prove that the tangent at any point of a circle is perpendicular to the radius through the point of contact.',
    solution: { steps: ['Let $O$ be the centre and $AB$ a tangent touching the circle at $P$.', 'Suppose $OP$ is not perpendicular to $AB$. Draw $OQ \\perp AB$, meeting $AB$ at $Q$.', 'Then $OQ < OP$. But $Q$ lies on the tangent line, so $Q$ is outside the circle, giving $OQ > OP$.', 'Contradiction, hence $OP \\perp AB$.'], answerLatex: 'OP \\perp AB \\text{ (proved)}' },
    tags: ['proof', 'perpendicular', 'radius'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Circles', 6),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Circles', topic: 'Tangent from External Point',
    subtopic: 'Tangent length', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'A point $P$ is $26$ cm away from the centre $O$ of a circle of radius $10$ cm. $PA$ is a tangent from $P$ to the circle. Find the length of $PA$.',
    solution: { steps: ['$PA \\perp OA$, so triangle $AOP$ is right angled at $A$', '$PA = \\sqrt{OP^2 - OA^2} = \\sqrt{26^2 - 10^2} = \\sqrt{576} = 24$ cm'], answerLatex: '24 \\text{ cm}' },
    tags: ['tangent', 'pythagoras'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Circles', 7),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Circles', topic: 'Angle Properties',
    subtopic: 'Two tangents from point', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'From an external point $P$, two tangents $PA$ and $PB$ are drawn to a circle with centre $O$. If $\\angle APB = 50^\\circ$, find $\\angle OAB$.',
    solution: { steps: ['$OA \\perp PA$ and $OB \\perp PB$', 'In quadrilateral $PAOB$: $\\angle AOB = 360 - 90 - 90 - 50 = 130^\\circ$', 'Triangle $AOB$ is isosceles with $OA = OB$', '$\\angle OAB = \\frac{180 - 130}{2} = 25^\\circ$'], answerLatex: '25^\\circ' },
    tags: ['tangents', 'angle', 'quadrilateral'], source: 'CBSE 2022 Board',
  },
];

// ─── Areas Related to Circles ───────────────────────────────
const areasCircles: Question[] = [
  {
    id: makeId('Areas Related to Circles', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Areas Related to Circles', topic: 'Area of Sector',
    subtopic: 'Sector area', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the area of a sector of a circle with radius $7$ cm and central angle $90^\\circ$. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$A = \\frac{\\theta}{360} \\times \\pi r^2 = \\frac{90}{360} \\times \\frac{22}{7} \\times 49 = \\frac{1}{4} \\times 154 = 38.5$ cm$^2$'], answerLatex: '38.5 \\text{ cm}^2' },
    tags: ['sector', 'area'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Areas Related to Circles', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Areas Related to Circles', topic: 'Area of Segment',
    subtopic: 'Segment area', difficulty: 'medium', marks: 3, estimatedMinutes: 6,
    questionLatex: 'Find the area of the minor segment of a circle with radius $14$ cm and central angle $90^\\circ$. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['Area of sector = $\\frac{90}{360} \\times \\frac{22}{7} \\times 196 = 154$ cm$^2$', 'Area of triangle = $\\frac{1}{2} \\times 14 \\times 14 = 98$ cm$^2$', 'Area of segment = $154 - 98 = 56$ cm$^2$'], answerLatex: '56 \\text{ cm}^2' },
    tags: ['segment', 'area'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Areas Related to Circles', 3),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Areas Related to Circles', topic: 'Area of Ring',
    subtopic: 'Concentric circles', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the area of a ring whose outer radius is $21$ cm and inner radius is $14$ cm. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['Area of ring = $\\pi(R^2 - r^2)$', '$= \\frac{22}{7} \\times (21^2 - 14^2) = \\frac{22}{7} \\times 245$', '$= 22 \\times 35 = 770$ cm$^2$'], answerLatex: '770 \\text{ cm}^2' },
    tags: ['ring', 'area', 'concentric'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Areas Related to Circles', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Areas Related to Circles', topic: 'Area of Circle',
    subtopic: 'Circle area', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the area of a circle of radius $10.5$ cm. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$A = \\pi r^2 = \\frac{22}{7} \\times 10.5 \\times 10.5 = 346.5$ cm$^2$'], answerLatex: '346.5 \\text{ cm}^2' },
    tags: ['circle', 'area'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Areas Related to Circles', 5),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Areas Related to Circles', topic: 'Area of Sector',
    subtopic: 'Sector area', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'Find the area of a sector of a circle of radius $21$ cm with central angle $120^\\circ$. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$A = \\frac{\\theta}{360} \\times \\pi r^2 = \\frac{120}{360} \\times \\frac{22}{7} \\times 441$', '$= \\frac{1}{3} \\times 22 \\times 63 = 462$ cm$^2$'], answerLatex: '462 \\text{ cm}^2' },
    tags: ['sector', 'area'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Areas Related to Circles', 6),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Areas Related to Circles', topic: 'Area of Sector',
    subtopic: 'Minute hand', difficulty: 'medium', marks: 2, estimatedMinutes: 4,
    questionLatex: 'The minute hand of a clock is $21$ cm long. Find the area swept by it in $20$ minutes. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['In $20$ minutes the hand sweeps $\\frac{20}{60} \\times 360 = 120^\\circ$', '$A = \\frac{120}{360} \\times \\frac{22}{7} \\times 21^2 = \\frac{1}{3} \\times 22 \\times 63 = 462$ cm$^2$'], answerLatex: '462 \\text{ cm}^2' },
    tags: ['minute-hand', 'sector', 'area'], source: 'CBSE 2022 Board',
  },
];

// ─── Surface Areas and Volumes ──────────────────────────────
const surfaceVolumes: Question[] = [
  {
    id: makeId('Surface Areas and Volumes', 1),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Surface Areas and Volumes', topic: 'Cylinder',
    subtopic: 'Surface area', difficulty: 'easy', marks: 1, estimatedMinutes: 2,
    questionLatex: 'Find the curved surface area of a cylinder with radius $7$ cm and height $10$ cm.',
    solution: { steps: ['CSA $= 2\\pi rh = 2 \\times \\frac{22}{7} \\times 7 \\times 10 = 440$ cm$^2$'], answerLatex: '440 \\text{ cm}^2' },
    tags: ['cylinder', 'csa'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Surface Areas and Volumes', 2),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Surface Areas and Volumes', topic: 'Combination',
    subtopic: 'Solid combination', difficulty: 'hard', marks: 4, estimatedMinutes: 8,
    questionLatex: 'A tent is in the shape of a cylinder surmounted by a conical top. If the height of the cylinder is $2.1$ m and its diameter is $4$ m, and the slant height of the top is $2.8$ m, find the area of canvas used. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['Cylinder: $r = 2$ m, $h = 2.1$ m', 'CSA $= 2\\pi rh = 2 \\times \\frac{22}{7} \\times 2 \\times 2.1 = 26.4$ m$^2$', 'Cone: $r = 2$ m, $l = 2.8$ m', 'CSA $= \\pi rl = \\frac{22}{7} \\times 2 \\times 2.8 = 17.6$ m$^2$', 'Total canvas $= 26.4 + 17.6 = 44$ m$^2$'], answerLatex: '44 \\text{ m}^2' },
    tags: ['combination', 'tent'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Surface Areas and Volumes', 3),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Surface Areas and Volumes', topic: 'Sphere',
    subtopic: 'Volume', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the volume of a sphere of radius $3.5$ cm. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$V = \\frac{4}{3}\\pi r^3 = \\frac{4}{3} \\times \\frac{22}{7} \\times (3.5)^3 = \\frac{4}{3} \\times \\frac{22}{7} \\times 42.875 = 179.67$ cm$^3$'], answerLatex: '179.67 \\text{ cm}^3' },
    tags: ['sphere', 'volume'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Surface Areas and Volumes', 4),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Surface Areas and Volumes', topic: 'Cone',
    subtopic: 'Curved surface area', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the curved surface area of a cone of radius $7$ cm and slant height $14$ cm. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['CSA $= \\pi rl = \\frac{22}{7} \\times 7 \\times 14 = 308$ cm$^2$'], answerLatex: '308 \\text{ cm}^2' },
    tags: ['cone', 'csa'], source: 'CBSE 2024 Sample',
  },
  {
    id: makeId('Surface Areas and Volumes', 5),
    board: 'CBSE', year: 2022, paperType: 'board', chapter: 'Surface Areas and Volumes', topic: 'Cone',
    subtopic: 'Volume', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the volume of a cone of radius $6$ cm and height $8$ cm. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$V = \\frac{1}{3}\\pi r^2 h = \\frac{1}{3} \\times \\frac{22}{7} \\times 36 \\times 8$', '$= \\frac{2112}{7}$ cm$^3$'], answerLatex: '\\frac{2112}{7} \\text{ cm}^3' },
    tags: ['cone', 'volume'], source: 'CBSE 2022 Board',
  },
  {
    id: makeId('Surface Areas and Volumes', 6),
    board: 'CBSE', year: 2023, paperType: 'board', chapter: 'Surface Areas and Volumes', topic: 'Conversion',
    subtopic: 'Cuboid to spheres', difficulty: 'hard', marks: 3, estimatedMinutes: 6,
    questionLatex: 'A cuboid of dimensions $66 \\times 42 \\times 21$ cm is melted and recast into spheres of diameter $4.2$ cm. Find the number of spheres formed. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['Volume of cuboid $= 66 \\times 42 \\times 21 = 58212$ cm$^3$', 'Radius of sphere $= 2.1$ cm', '$V_{sphere} = \\frac{4}{3} \\times \\frac{22}{7} \\times (2.1)^3 = 38.808$ cm$^3$', 'Number $= \\frac{58212}{38.808} = 1500$'], answerLatex: '1500' },
    tags: ['conversion', 'melt', 'recast'], source: 'CBSE 2023 Board',
  },
  {
    id: makeId('Surface Areas and Volumes', 7),
    board: 'CBSE', year: 2024, paperType: 'sample', chapter: 'Surface Areas and Volumes', topic: 'Cylinder',
    subtopic: 'Volume', difficulty: 'medium', marks: 2, estimatedMinutes: 3,
    questionLatex: 'Find the volume of a cylinder of radius $3$ m and height $3.5$ m. (Take $\\pi = \\frac{22}{7}$)',
    solution: { steps: ['$V = \\pi r^2 h = \\frac{22}{7} \\times 9 \\times 3.5 = 99$ m$^3$'], answerLatex: '99 \\text{ m}^3' },
    tags: ['cylinder', 'volume'], source: 'CBSE 2024 Sample',
  },
];

// ─── Export All Seed Data ────────────────────────────────────
export const SEED_QUESTIONS: Question[] = [
  ...realNumbers,
  ...polynomials,
  ...linearEquations,
  ...quadraticEquations,
  ...arithmeticProgressions,
  ...triangles,
  ...coordinateGeometry,
  ...trigonometry,
  ...trigApplications,
  ...statistics,
  ...probability,
  ...circles,
  ...areasCircles,
  ...surfaceVolumes,
];
